apiVersion: v1
data:
  apiToken: ZHQwYzAxLlo0RllYSUVaUUNCRFFYUExHUjNKTDNVUy5GSEtWSlVUUkk1Tlc1MkZIMkNFRlFFTlpWUlg1N1NNSllCNEhBVDZIR0VBSVRZNFNORURIREEyV0dOTTZLT0VE
  dataIngestToken: ZHQwYzAxLlY0QUhJSlRPVFhSR0gyRFFEQUNGV0RFNi5JM1c0QU9YUkpPV0ZPTVcyWkkzQTNHWVdPNFdMSDRBTEdXU0hCNllTQVVDRDc0WlhUUVVSMlRETUVSSVBGS1NH
kind: Secret
metadata:
  name: other-k8s-2025-11-25-1764059286
  namespace: dynatrace
  labels:
    dynatrace.com/created-by: "dynatrace.kubernetes"
type: Opaque
---
apiVersion: dynatrace.com/v1beta5
kind: DynaKube
metadata:
  name: other-k8s-2025-11-25-1764059286
  namespace: dynatrace
  labels:
    dynatrace.com/created-by: "dynatrace.kubernetes"
  annotations:
    feature.dynatrace.com/k8s-app-enabled: "true"
# Link to api reference for further information: https://docs.dynatrace.com/docs/ingest-from/setup-on-k8s/reference/dynakube-parameters
spec:
  apiUrl: https://rxx02969.live.dynatrace.com/api
  metadataEnrichment:
    enabled: true
  oneAgent:
    cloudNativeFullStack:
      tolerations:
        - effect: NoSchedule
          key: node-role.kubernetes.io/master
          operator: Exists
        - effect: NoSchedule
          key: node-role.kubernetes.io/control-plane
          operator: Exists
  activeGate:
    capabilities:
      - routing
      - kubernetes-monitoring
      - debugging
    resources:
      requests:
        cpu: 500m
        memory: 1.5Gi
      limits:
        cpu: 1000m
        memory: 1.5Gi
  logMonitoring: {}
  telemetryIngest:
    protocols:
      - jaeger
      - otlp
      - statsd
      - zipkin
    serviceName: telemetry-ingest
