apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumer-service
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consumer-service
  template:
    metadata:
      labels:
        app: consumer-service
    spec:
      containers:
        - name: consumer-service
          image: "vivien8/consumer-service:latest"
          ports:
            - containerPort: 3000
          env:
            - name: KAFKA_BROKER
              value: "kafka.dev.svc.cluster.local:9092"