apiVersion: v1
kind: Service
metadata:
  name: producer-service
  namespace: dev
  labels:
    app: producer-service
spec:
  type: ClusterIP
  selector:
    app: producer-service
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 3000